### ISSUE TITLE
邮件发送错误

### ISSUE THREAD

**Issue by Jiale23** [pu-client/oyasumi#8]
![img](https://s2.loli.net/2024/04/18/sL8lN1n3khfJMR9.jpg)
如题，和最后一行日志，启动成功邮件会报greeting never received

**Comment by seiuna** [comment]
https://github.com/nodemailer/nodemailer/issues/441 这个?

**Comment by Jiale23** [comment]
> [nodemailer/nodemailer#441](https://github.com/nodemailer/nodemailer/issues/441) 这个?

应该是，前几天没更新就没这个问题
